### ISSUE TITLE
docs: add section for Status of Project

### ISSUE THREAD

**Issue by ViRu-ThE-ViRuS** [romgrk/kui.nvim#1]
this is a plugin with HUGE potential, and it will be helpful to have these sections in a `wiki` or in a section of the `README.md` for plugin authors AND plugin users to see the status of this project, and where / how can they use it (directly or indirectly).

**sections to consider:** 
- status of project (scope, missing features, completed features, required help, references etc)
- usage (plugins using this if any) [ consider adding the demo to this section as well ]

**Comment by romgrk** [comment]
Updated the readme. AFAIK https://github.com/romgrk/kirby.nvim is the only place where this is used.

If the readme doesn't cover enough details let me know.
