### ISSUE TITLE
Question: How it renders?

### ISSUE THREAD

**Issue by EpsilonKu** [romgrk/kui.nvim#2]
Seems like `kui-demo.nvim` and `kirby.nvim` are float.  But I want to draw on buffer. If user move(resize, close etc.) buffer, rendered side also effect. Is it possible?

**Comment by romgrk** [comment]
This is based on hologram.nvim with a few additions so yes, it can work, but kui.nvim doesn't implement that use case. The [legacy folder](https://github.com/romgrk/kui.nvim/tree/master/lua/kui/legacy) contains the code from hologram (to be rewritten maybe).

Hologram is used [here](https://github.com/romgrk/kui.nvim/blob/228e3183ebfb5e18bf34030c0b35e63a757665eb/src/core/view/ViewSystem.ts#L94-L98) so there's just some wiring missing to connect the image to a particular buffer. 

But overall to get this to a production ready state it would probably need about 5-15 hours of work.
